TOPIC_ROBUD_CHATGPT_NEW_CHAT = "robud/robud_chatgpt/new_chat"
TOPIC_ROBUD_CHATGPT_SYSTEM_MESSAGE = "robud/robud_chatgpt/system_message"
TOPIC_ROBUD_CHATGPT_USER_MESSAGE = "robud/robud_chatgpt/user_message"
TOPIC_ROBUD_CHATGPT_RESPONSE_MESSAGE = "robud/robud_chatgpt/response_message"
TOPIC_ROBUD_CHATGPT_END_CHAT = "robud/robud_chatgpt/end_chat"
